---
name: Checks

on:
  pull_request:
    branches: [main]

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-20.04
    uses: ./github/workflows/test-and-lint.yml

    secrets:
      DOCKERHUB_USER: ${{ vars.DOCKERHUB_USER }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
